#!/usr/bin/env python3
import sys
import os
script_path = os.path.abspath(__file__)
script_dir = os.path.dirname(script_path)
src_dir = os.path.join(script_dir, "src")
sys.path.append(src_dir)

import typer
from cli import app
if __name__ == "__main__":
    app()
